if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="PBank-49";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

pair A,B,C,D,E,F,G,H,J;
A=(20,20(2+sqrt(2)));
B=(20(1+sqrt(2)),20(2+sqrt(2)));
C=(20(2+sqrt(2)),20(1+sqrt(2)));
D=(20(2+sqrt(2)),20);
E=(20(1+sqrt(2)),0);
F=(20,0);
G=(0,20);
H=(0,20(1+sqrt(2)));
J=(10(2+sqrt(2)),10(2+sqrt(2)));
draw(A--B);
draw(B--C);
draw(C--D);
draw(D--E);
draw(E--F);
draw(F--G);
draw(G--H);
draw(H--A);
dot(A);
dot(B);
dot(C);
dot(D);
dot(E);
dot(F);
dot(G);
dot(H);
dot(J);
label("A",A,NNW);
label("B",B,NNE);
label("C",C,ENE);
label("D",D,ESE);
label("E",E,SSE);
label("F",F,SSW);
label("G",G,WSW);
label("H",H,WNW);
label("J",J,SE);
