if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="PBank-24";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(7cm);
pair A,B,C,D,E,P;
A=(0,0);
B=(80,0);
C=(20,40);
D=(50,20);
E=(40,0);
P=(33.3,13.3);
draw(A--B);
draw(B--C);
draw(A--C);
draw(C--E);
draw(A--D);
draw(D--E);
dot(A);
dot(B);
dot(C);
dot(D);
dot(E);
dot(P);
label("A",A,SSW);
label("B",B,SSE);
label("C",C,NNW);
label("D",D,ENE);
label("E",E,SSE);
label("P",P,SSW);
